// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQlroW6cpF6sdUiG-1aYXkHty86kL-KGE',
    appId: '1:352603513305:web:14b9ee4ae0604c277ef9c8',
    messagingSenderId: '352603513305',
    projectId: 'demo2-ac717',
    authDomain: 'demo2-ac717.firebaseapp.com',
    storageBucket: 'demo2-ac717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU97CqjhrqNsyV_1p5w_4m-GMU78VunOs',
    appId: '1:352603513305:android:506e8f85f4809bb77ef9c8',
    messagingSenderId: '352603513305',
    projectId: 'demo2-ac717',
    storageBucket: 'demo2-ac717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhp3TEJi2dUYEf9O36V50JQuHRIyqhMQ',
    appId: '1:352603513305:ios:d42fb6f3f411321d7ef9c8',
    messagingSenderId: '352603513305',
    projectId: 'demo2-ac717',
    storageBucket: 'demo2-ac717.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuhp3TEJi2dUYEf9O36V50JQuHRIyqhMQ',
    appId: '1:352603513305:ios:d42fb6f3f411321d7ef9c8',
    messagingSenderId: '352603513305',
    projectId: 'demo2-ac717',
    storageBucket: 'demo2-ac717.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQlroW6cpF6sdUiG-1aYXkHty86kL-KGE',
    appId: '1:352603513305:web:71a40706480a8ec47ef9c8',
    messagingSenderId: '352603513305',
    projectId: 'demo2-ac717',
    authDomain: 'demo2-ac717.firebaseapp.com',
    storageBucket: 'demo2-ac717.firebasestorage.app',
  );
}
